kogito.codegen.process.section=true
quarkus.kogito.process.returns-process-instance=false
quarkus.swagger-ui.always-include=true

inventory.CART-001=10
inventory.CART-002=5
inventory.CART-003=2
inventory.CART-004=1
inventory.CART-005=0
